### ISSUE TITLE
File uploading feature is not available

### ISSUE THREAD

**Issue by bennettstandler** [althealouis/Real-Time-Chat-Application#2]
### Add the file uploading feature in the ui also the uploaded files should be saved in the backend.

**Comment by vedikapagar** [comment]
I want to work on this issue; can you give some more information regarding the same?

**Comment by bennettstandler** [comment]
There is a feature in the application UI to share documents in the chat, but it does not have any functionality. Your task is to make it functionable.

**Comment by althealouis** [comment]
> I want to work on this issue; can you give some more information regarding the same?

**Comment by vedikapagar** [comment]
Okay, assign me this issue

**Comment by bennettstandler** [comment]
The issue has been solved hence closed
